ALTER SESSION SET CONTAINER = ORCLPDB1;

GRANT CONNECT TO scrapper CONTAINER=CURRENT;
GRANT CREATE SESSION TO scrapper CONTAINER=CURRENT;
GRANT RESOURCE TO scrapper CONTAINER=CURRENT;

ALTER USER scrapper QUOTA 100M ON USERS;